# Generated by Django 4.2.23 on 2025-11-30 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("card_number", models.PositiveBigIntegerField()),
                ("pin", models.PositiveBigIntegerField()),
                ("balance", models.CharField(max_length=25)),
                ("delivery_method", models.CharField(max_length=250)),
                ("receiver_first_name", models.CharField(max_length=250)),
                ("receiver_last_name", models.CharField(max_length=250)),
                ("receiver_address", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("sender_full_name", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OfferType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        error_messages={
                            "unique": "This coupon has already been created."
                        },
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                ("min_order_total", models.PositiveIntegerField()),
                ("num_available", models.PositiveIntegerField()),
                ("num_used", models.PositiveIntegerField(default=0)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="BuzzOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("offer_name", models.CharField(blank=True, max_length=100, null=True)),
                ("meta_description", models.TextField(blank=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("flat", "Flat Amount")],
                        default="percentage",
                        max_length=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "offer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="offer.offertype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="productapp.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
