# Generated by Django 4.2.23 on 2025-11-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("todo_name", models.CharField(max_length=255)),
                ("todo_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("incomp", "INCOMPLETE"), ("comp", "COMPLETE")],
                        default="incomp",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "ToDoList",
                "verbose_name_plural": "ToDoList",
            },
        ),
    ]
