# Generated by Django 4.2.23 on 2025-11-30 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkoutapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "flat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Flat rate (AUD)",
                        max_digits=8,
                    ),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Free shipping threshold (AUD)",
                        max_digits=8,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Delivery Charge",
                "verbose_name_plural": "Delivery Charges",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("slug", models.SlugField(max_length=128, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="payment_methods/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="payment_methods/thumbnails/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("client_id", models.CharField(blank=True, max_length=250, null=True)),
                ("public_key", models.CharField(blank=True, max_length=250, null=True)),
                ("secret_key", models.CharField(blank=True, max_length=250, null=True)),
                ("extra_args", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount in smallest currency unit (e.g. paisa, cents)",
                        max_digits=8,
                    ),
                ),
                ("currency", models.CharField(default="NPR", max_length=10)),
                (
                    "provider",
                    models.CharField(
                        help_text="Payment provider name (e.g., khalti, stripe)",
                        max_length=50,
                    ),
                ),
                (
                    "intent_id",
                    models.CharField(
                        blank=True,
                        help_text="third party intent id or transaction id by which we can verify",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("dispute", "Dispute"),
                            ("reverted", "Reverted"),
                            ("settled", "Settled"),
                            ("penalty", "Penalty"),
                        ],
                        default="initiated",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("chargeback", "Chargeback"),
                        ],
                        default="payment",
                        max_length=20,
                    ),
                ),
                ("extra_data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_orders",
                        to="checkoutapp.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="This field is useful only when the txn type is receipt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="checkoutapp.orderitem",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        default=uuid.UUID("ec0bf2c9-8322-4045-b918-1770e8e764c1"),
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transaction_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transaction_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers_payment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_payment",
                        to="checkoutapp.order",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="paymentapp.paymentmethod",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
