# Generated by Django 4.2.23 on 2025-12-14 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paymentapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                default=uuid.UUID("c5b2d6f2-6121-4875-a353-b960b952e5d4"),
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="transaction_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
