import { CipherDashboardRoutesProps } from '@cagtu-cms/util-formatter';
import {
    IconAddressBook,
    IconAffiliate,
    IconAt,
    IconPhone,
    IconAward,
    IconCash,
    IconChartHistogram,
    IconDashboard,
    IconDiscount2,
    IconFileStar,
    IconHeadset,
    IconListDetails,
    IconMessageCircle2,
    IconNotes,
    IconSpeakerphone,
    IconTool,
    IconUsers,
    IconWorld, IconBadge4k, IconBadge,
    IconShoppingBag,
    IconPackage,
    IconCamera
} from '@tabler/icons';

export const dashboardRoutes: CipherDashboardRoutesProps[] = [
    {
        path: 'dashboard',
        key: 'dashboard',
        name: 'Dashboard',
        permissionName: 'public',
        icon: <IconDashboard stroke={1.75} />,
    },
    {
        path: 'cms',
        key: 'cms',
        name: 'CMS',
        icon: <IconAffiliate stroke={1.75} />,
        hasChild: true,
        permissions: [
            //must include children permissionName here
            'view_category',
            'view_task',
            'view_skill',
            'view_topskill',
            'view_topcategory',
            'view_successstory',
            'view_trustedpartner',
            'view_securityquestion',
            'view_candidate',
            'view_horoscope',
            'view_blog',
            'view_vacancy',
            'view_content',
            'view_notice',
            'view_faq',
        ],
        children: [
            {
                path: '/categories',
                key: 'categories',
                name: 'Categories',
                permissionName: 'view_category',
            },

            {
                path: '/recommend',
                key: 'task_recommend',
                name: 'Task Recommend',
                permissionName: 'view_task',
            },
            {
                path: '/skills',
                key: 'skills',
                name: 'Skills',
                permissionName: 'view_skill',
            },
            {
                path: '/top-skills',
                key: 'topSkills',
                name: 'Top Skills',
                permissionName: 'view_topskill',
            },
            {
                path: '/top-categories',
                key: 'topCategories',
                name: 'Top Categories',
                permissionName: 'view_topcategory',
            },
            {
                path: '/success-stories',
                key: 'success_stories',
                name: 'Success Stories',
                permissionName: 'view_successstory',
            },
            {
                path: '/trusted-partners',
                key: 'trusted_partners',
                name: 'Trusted Partners',
                permissionName: 'view_trustedpartner',
            },
            {
                path: '/security-question',
                key: 'security_question',
                name: 'Security Question',
                permissionName: 'view_securityquestion',
            },
            {
                path: '/candidates',
                key: 'candidates',
                name: 'Candidates',
                permissionName: 'view_candidate',
            },
            {
                path: '/horoscope',
                key: 'horoscope',
                name: 'Horoscope',
                permissionName: 'view_horoscope',
            },
            {
                path: '/blog',
                key: 'blog',
                name: 'Blog',
                permissionName: 'view_blog',
            },
            {
                path: '/career',
                key: 'career',
                name: 'Career',
                permissionName: 'view_vacancy',
            },
            {
                path: '/legal',
                key: 'legal',
                name: 'Legal',
                permissionName: 'view_content',
            },
            {
                path: '/notice',
                key: 'notice',
                name: 'Notice',
                permissionName: 'view_notice',
            },
            {
                path: '/faq',
                key: 'faq',
                name: 'FAQs',
                permissionName: 'view_faq',
            },
        ],
    },
    {
        path: 'task',
        key: 'task',
        name: 'Task',
        icon: <IconListDetails stroke={1.75} />,
        hasChild: true,
        permissions: ['view_entityservice', 'view_task', 'view_booking', 'view_order'], //must include children permissionName here if there is any children
        children: [
            {
                path: '/entity-service',
                key: 'entity_service',
                name: 'Entity Service',
                permissionName: 'view_entityservice',
            },
            {
                path: '/assigned-task',
                key: 'assigned_task',
                name: 'Assigned Task',
                permissionName: 'view_task',
            },
            {
                path: '/bookings/pending',
                key: 'task_bookings',
                name: 'Bookings',
                permissionName: 'view_booking',
            },
            {
                path: '/orders',
                key: 'task_orders',
                name: 'Orders',
                permissionName: 'view_order',
            },
        ],
    },
    {
        path: 'services',
        key: 'services',
        name: 'Services',
        icon: <IconTool stroke={1.75} />,
        permissionName: 'view_service',
    },
    //changed from user-groups to user-roles as per request
    {
        path: 'user-roles',
        key: 'user_roles',
        name: 'Users & Roles',
        icon: <IconUsers stroke={1.75} />,
        hasChild: true,
        permissions: ['view_user', 'view_role'],
        children: [
            {
                path: '/users',
                key: 'users',
                name: 'Users',
                permissionName: 'view_user',
            },
            {
                path: '/roles',
                key: 'roles',
                name: 'Roles',
                permissionName: 'view_role',
            },
        ],
    },
    {
        path: 'kyc-&-compliance',
        key: 'kyc_&_compliance',
        name: 'KYC & Compliance',
        icon: <IconNotes stroke={1.75} />,
        hasChild: true,
        permissions: ['view_documenttype', 'view_kyc'],
        children: [
            {
                path: '/kyc-documents',
                key: 'kyc_documents',
                name: 'KYC Documents',
                permissionName: 'view_documenttype',
            },
            {
                path: '/kyc-verification',
                key: 'kyc_verification',
                name: 'KYC Verification',
                permissionName: 'view_kyc',
            },
        ],
    },
    {
        path: 'merchant',
        key: 'merchant',
        name: 'Merchant',
        icon: <IconPhone stroke={1.75} />,
        hasChild: false,
        permissions: ['merchant'],

    },
    {
        path: '',
        key: 'product/shop',
        name: 'Stock Management',
        icon: <IconPackage stroke={1.75} />,
        hasChild: true,
        permissions: ['product-upload', 'view_offer', 'view_offerredeem'],
        children: [
            {
                path: 'product',
                key: 'product',
                name: 'Product',
                permissionName: 'product',
               
            },
          
            {
                path: 'shop',
                key: 'shop',
                name: 'Shop',
                permissionName: 'shop',
            },
             {
                path: 'shop-config/shop',
                key: 'shop-config',
                name: 'Shop Configuration',
                permissionName: 'shop-config',
            },
        ],
    },
    {
        path: 'analytics',
        key: 'analytics',
        name: 'Analytics',
        icon: <IconChartHistogram stroke={1.75} />,
        hasChild: true,
        permissions: [
            'view_user_analytics',
            'view_category_analytics',
            'view_entity_service_analytics',
            'view_task_analytics',
            'view_booking_analytics',
            'view_offer_analytics',
            'view_payment_analytics',
            'view_product_analytics',
            'view_shop_analytics',
            'view_merchant_analytics',
        ],
        children: [
            {
                path: '/user',
                key: 'user',
                name: 'User',
                permissionName: 'view_user_analytics',
            },
            {
                path: '/category',
                key: 'category',
                name: 'Category',
                permissionName: 'view_category_analytics',
            },
            {
                path: '/entity-service',
                key: 'entity_service',
                name: 'Entity Service',
                permissionName: 'view_entity_service_analytics',
            },
            {
                path: '/assigned-task',
                key: 'assigned-task',
                name: 'Assigned Task',
                permissionName: 'view_task_analytics',
            },
            {
                path: '/booking',
                key: 'booking',
                name: 'Booking',
                permissionName: 'view_booking_analytics',
            },
            {
                path: '/offer',
                key: 'offer',
                name: 'Offer',
                permissionName: 'view_offer_analytics',
            },
            {
                path: '/payment',
                key: 'payment',
                name: 'Payment',
                permissionName: 'view_payment_analytics',
            },
            {
                path: '/product-analytics',
                key: 'product_analytics',
                name: 'Product Analytics',
                permissionName: 'view_product_analytics',
            },
            {
                path: '/shop-analytics',
                key: 'shop_analytics',
                name: 'Shop Analytics',
                permissionName: 'view_shop_analytics',
            },
            {
                path: '/merchant-analytics',
                key: 'merchant_analytics',
                name: 'Merchant Analytics',
                permissionName: 'view_merchant_analytics',
            },
        ],
    },
    {
        path: 'offer',
        key: 'offer',
        name: 'Offer',
        icon: <IconDiscount2 stroke={1.75} />,
        hasChild: true,
        permissions: ['view_offerrule', 'view_offer', 'view_offerredeem'],
        children: [
            {
                path: '/offer-rule',
                key: 'offer_rule',
                name: 'Offer Rule',
                permissionName: 'view_offerrule',
            },
            {
                path: '/service-offer',
                key: 'service_offer',
                name: 'Service Offer',
                permissionName: 'view_offer',
            },
            {
                path: '/redeemption',
                key: 'redeemption',
                name: 'Redeemption',
                permissionName: 'view_offerredeem',
            },
        ],
    },
    {
        path: 'referral',
        key: 'referral',
        name: 'Referrals',
        icon: <IconDiscount2 stroke={1.75} />,
        hasChild: true,
        permissions: ['view_referral'],
        children: [
            {
                path: '/list',
                key: 'list',
                name: 'Referral List',
                permissionName: 'view_referral',
            },
        ],
    },
    {
        path: 'rewards',
        key: 'rewards',
        name: 'Rewards',
        icon: <IconAward stroke={1.75} />,
        hasChild: true,
        permissions: ['view_rewardrule', 'view_badge', 'view_reward'],
        children: [
            {
                path: '/rewards-list',
                key: 'rewards_list',
                name: 'Rewards list',
                permissionName: 'view_reward',
            },
            {
                path: '/rewards-rule',
                key: 'rewards_rule',
                name: 'Rewards Rule',
                permissionName: 'view_rewardrule',
            },
            {
                path: '/badge',
                key: 'badge',
                name: 'Badge',
                permissionName: 'view_badge',
            },
        ],
    },
    {
        path: 'ratings',
        key: 'ratings',
        name: 'Ratings',
        icon: <IconFileStar stroke={1.75} />,
        hasChild: true,
        permissions: ['view_rating'],
        children: [
            {
                path: '/rating-list',
                key: 'rating_list',
                name: 'Rating list',
                permissionName: 'view_rating',
            },
        ],
    },
    {
        path: 'payment',
        key: 'payment',
        name: 'Payment',
        icon: <IconCash stroke={1.75} />,
        hasChild: true,
        permissions: ['view_transaction', 'view_booking', 'view_withdraw', 'view_approve'],
        children: [
            {
                path: '/transaction-history',
                key: 'transaction_history',
                name: 'Transaction History',
                permissionName: 'view_transaction',
            },
            {
                path: '/refund-request',
                key: 'refund-request',
                name: 'Refund Request',
                permissionName: 'view_booking',
            },
            {
                path: '/withdraw-request',
                key: 'withdraw-request',
                name: 'Withdraw',
                permissionName: 'view_withdraw',
            },
            // {
            //     path: '/approve-request',
            //     key: 'approve-request',
            //     name: 'Approve',
            //     permissionName: 'view_approve',
            // },
        ],
    },
    {
        path: 'marketing',
        key: 'marketing',
        name: 'Marketing',
        icon: <IconSpeakerphone stroke={1.75} />,
        hasChild: true,
        permissions: ['view_advertisement'],
        children: [
            // {
            //     path: 'marketing/success-stories',
            //     key: 'success_stories',
            //     name: 'Success Stories',
            // },
            // {
            //     path: 'marketing/trusted-partners',
            //     key: 'trusted_partners',
            //     name: 'Trusted Partners',
            // },
            {
                path: '/advertisement',
                key: 'advertisement',
                name: 'Advertisement',
                permissionName: 'view_advertisement',
            },
        ],
    },
    {
        path: 'locale',
        key: 'locale',
        name: 'Locale',
        icon: <IconWorld stroke={1.75} />,
        hasChild: true,
        permissions: ['view_currency', 'view_exchangerate', 'view_language', 'view_city', 'view_country', 'view_bank'],
        children: [
            {
                path: '/currency',
                key: 'currency',
                name: 'Currency',
                permissionName: 'view_currency',
            },
            {
                path: '/exchange-rate',
                key: 'exchange_rate',
                name: 'Exchange Rate',
                permissionName: 'view_exchangerate',
            },
            {
                path: '/language',
                key: 'language',
                name: 'Language',
                permissionName: 'view_language',
            },
            {
                path: '/city',
                key: 'city',
                name: 'City',
                permissionName: 'view_city',
            },
            {
                path: '/country',
                key: 'country',
                name: 'Country',
                permissionName: 'view_country',
            },
            {
                path: '/bank',
                key: 'bank',
                name: 'Bank',
                permissionName: 'view_bank',
            },
        ],
    },
    {
        path: 'email',
        key: 'email',
        name: 'Email',
        icon: <IconAt stroke={1.75} />,
        hasChild: true,
        permissions: ['view_senderemail', 'view_newsletter', 'view_emailtemplate'],
        children: [
            {
                path: '/sender-email',
                key: 'sender_email',
                name: 'Sender Email',
                permissionName: 'view_senderemail',
            },
            {
                path: '/newsletter',
                key: 'newsletter',
                name: 'Newsletter',
                permissionName: 'view_newsletter',
            },
            {
                path: '/template',
                key: 'email_template',
                name: 'Template',
                permissionName: 'view_emailtemplate',
            },
        ],
    },
    {
        path: 'contact',
        key: 'contact',
        name: 'Contact',
        icon: <IconAddressBook stroke={1.75} />,
        hasChild: true,
        permissions: ['view_contactus', 'view_contactuscategory'],
        children: [
            {
                path: '/list',
                key: 'contact_list',
                name: 'List',
                permissionName: 'view_contactus',
            },
            {
                path: '/category',
                key: 'contact_category',
                name: 'Category',
                permissionName: 'view_contactuscategory',
            },
        ],
    },
    {
        path: 'support',
        key: 'support',
        name: 'Support',
        icon: <IconHeadset stroke={1.75} />,
        hasChild: true,
        permissions: ['change_supportticket', 'view_supportticket', 'view_supporttickettype', 'view_merchanttickettype', 'view_shoptickettype'],
        children: [
            {
                path: '/reports',
                key: 'reports',
                name: 'Reports',
                permissionName: 'change_supportticket',
            },
            {
                path: '/ticket',
                key: 'ticket',
                name: 'Ticket',
                permissionName: 'view_supportticket',
            },
            {
                path: '/ticket-type',
                key: 'ticket_type',
                name: 'Ticket Type',
                permissionName: 'view_supporttickettype',
            },
            {
                path: '/merchant-ticket',
                key: 'merchant_ticket_type',
                name: 'Merchant Ticket',
                permissionName: 'view_merchanttickettype',
            },
            {
                path: '/shop-ticket',
                key: 'shop_ticket_type',
                name: 'Shop Ticket',
                permissionName: 'view_shoptickettype',
            },

            // Not Required for now as it's api has been removed from backend if needed again simply uncomment code below

            // {
            //     path: '/help',
            //     key: 'help',
            //     name: 'Help',
            // },
            // {
            //     path: '/help-topic',
            //     key: 'help_topic',
            //     name: 'Help Topic',
            // },
        ],
    },
    {
        path: 'feedback',
        key: 'feedback',
        name: 'Feedback',
        icon: <IconMessageCircle2 stroke={1.75} />,
        hasChild: true,
        permissions: ['view_feedback', 'view_feedbackcategory'],
        children: [
            {
                path: '/list',
                key: 'list',
                name: 'List',
                permissionName: 'view_feedback',
            },
            {
                path: '/category',
                key: 'feedback_category',
                name: 'Category',
                permissionName: 'view_feedbackcategory',
            },
        ],
    },

    // Not Required for now as it's api has been removed from backend if needed again simply uncomment code below

    // {
    //     path: 'report',
    //     key: 'report',
    //     name: 'Report',
    //     icon: <IconFlag stroke={1.75} />,
    // },
];

export default dashboardRoutes;
