# Generated by Django 4.2.23 on 2025-11-30 10:13

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("quotes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/carousel/carousel/"
                    ),
                ),
                (
                    "header_banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/carousel/header/"
                    ),
                ),
                (
                    "footer_banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/carousel/footer/"
                    ),
                ),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Carousel"),
                            ("HDR", "Header "),
                            ("FTR", "Footer"),
                            ("ANN", "Announcement"),
                        ],
                        default="CAR",
                        max_length=3,
                    ),
                ),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "category_badge",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MasterProfileAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("suburb", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("postcode", models.CharField(blank=True, max_length=8, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MasterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("profile_name", models.CharField(max_length=120, null=True)),
                (
                    "profile_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/carousel/"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Include country code, e.g. +61XXXXXXXXX",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "hotline_number",
                    models.CharField(
                        blank=True,
                        help_text="Include country code, e.g. +61XXXXXXXXX",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "opening_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "closing_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("extra_info", models.JSONField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="master.masterprofileaddress",
                    ),
                ),
                ("banners", models.ManyToManyField(blank=True, to="master.banner")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="banner",
            name="master_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.masterprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="masterprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="unique_master_profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="banner",
            unique_together={("order", "banner_type", "master_profile")},
        ),
    ]
