# Generated by Django 4.2.23 on 2025-11-30 10:13

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "minor",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Enter the number of minors eg: 100 for cents to become 1 USD",
                    ),
                ),
                ("supports_stripe", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "current_value",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("enable_currency_configuration", models.BooleanField(default=False)),
                ("symbol", models.CharField(max_length=32, null=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ("-code",),
            },
        ),
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("sub_title", models.CharField(max_length=128)),
                ("image", models.ImageField(upload_to="cipher/user/media")),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "code",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("enable_language_configuration", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.CreateModel(
            name="PolicyAndTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Privacy", "Privacy Policy"),
                            ("Terms", "Terms of Condition"),
                        ],
                        default="Privacy",
                        max_length=50,
                    ),
                ),
                (
                    "Content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("Effective_Date", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HoroscopeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField()),
                ("description", models.CharField(max_length=1255)),
                ("sharing_url", models.URLField(blank=True, null=True)),
                (
                    "horoscope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.horoscope",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "value",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("enable_currency_configuration", models.BooleanField(default=False)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "ExchangeRate",
                "verbose_name_plural": "ExchangeRates",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=64)),
                ("local_name", models.CharField(max_length=128)),
                ("phone_code", models.CharField(max_length=5)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.currency",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("local_name", models.CharField(max_length=128)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "latitude",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "unique_together": {("country", "zip_code")},
            },
        ),
    ]
