export enum TITLE_TYPES {
    booking = "booking",
    booked = "booked",
    approval = "approval",
    approved = "Approved",
    status_completed = "status completed",
    status_closed = "status closed",
    created = "created",
    rejected = "Rejected",
    followed = "followed",
    payment_completed = "payment completed",
    cancelled = "cancelled",
    reward_earned = "reward_earned",
    accepted = "accepted",
    negotiated = "negotiated",
    kyc_document_submitted = "kyc_document_submitted",
    kyc_document_verified = "kyc_document_verified",
    kyc_document_rejected = "kyc_document_rejected",
    staff_assigned = "Staff Account Activated",
    staff_removed = "Staff Account Removal",
    shop_verified = "Shop Verified",
    shop_rejected = "Shop Rejected",
}
