# Generated by Django 4.2.23 on 2025-11-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the error occurred.",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        help_text="The type or class of the exception (e.g., ValueError, TypeError).",
                        max_length=255,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The detailed error message associated with the exception."
                    ),
                ),
                (
                    "stack_trace",
                    models.TextField(
                        blank=True,
                        help_text="The full stack trace, providing context for the error.",
                        null=True,
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True,
                        help_text="The URL path of the request that triggered the error.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Log",
                "verbose_name_plural": "Error Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
