const trending = [
 
  {
    id: 3,
    name: "Mitho Boondi Laddu",
    price: "5.5",
    description:
      "Ingredients: Milk, milk Powder, Vegetable oil, Cream, dried nuts, shredded coconut, Self raising flour, Sugar, Cardamom.",
    image: "../assets/fourteen.png",
    gram: 100,
    featured: true,
    bestSelling: true,
  },
  {
    id: 4,
    name: "Mitho Gulab Jamun",
    price: "7.75",
    description:
      "Ingredients: Flour, Besan, cornflour, soda, sugar, Ghee, Edible food Colour.",
    image: "../assets/ten.png",
    gram: 100,
    featured: true,
    bestSelling: false,
  },
  {
    id: 5,
    name: "Mitho Jalebi",
    price: "5.5",
    description: "Ingredients: cashew nuts, sugar, cardamom, silver leaf .",
    image: "../assets/thirteen.png",
    gram: 100,
    featured: true,
    bestSelling: true,
  },
  {
    id: 6,
    name: "Mitho Kaju Katli",
    price: "7.5",
    description: "Ingredients: Raw Cashew, Sugar, edible silver.",
    image: "../assets/six.png",
    gram: 100,
    featured: true,
    bestSelling: false,
  },
  {
    id: 7,
    name: "Mitho Kala Jamun",
    price: "6.5",
    description: "Ingredients: Gram flour, sugar, ghee, cardamom.",
    image: "../assets/twelve.png",
    gram: 100,
    featured: false,
    bestSelling: true,
  },
  {
    id: 8,
    name: "Mitho Kalakand",
    price: "6.5",
    description:
      "Ingredients: Milk, milk Powder, Vegetable oil, Cream, dried nuts, shredded coconut, Self raising flour, Sugar, Cardamom.",
    image: "../assets/four.png",
    gram: 100,
    featured: true,
    bestSelling: true,
  },
  {
    id: 9,
    name: "Mitho khuwa Almond Barfi",
    price: "6",
    description:
      "Ingredients: Flour, Besan, cornflour, soda, sugar, Ghee, Edible food Colour.",
    image: "../assets/three.png",
    gram: 100,
    featured: true,
    bestSelling: false,
  },
  {
    id: 10,
    name: "Mitho Milk Cake",
    price: "6.5",
    description: "Ingredients: cashew nuts, sugar, cardamom, silver leaf .",
    image: "../assets/eight.png",
    gram: 100,
    featured: true,
    bestSelling: true,
  },
  {
    id: 11,
    name: "Mitho Mixed Barfi",
    price: "6",
    description: "Ingredients: Raw Cashew, Sugar, edible silver.",
    image: "../assets/five.png",
    gram: 100,
    featured: true,
    bestSelling: false,
  },
  {
    id: 12,
    name: "Mitho Mixed Chamcham",
    price: "6.5",
    description: "Ingredients: Gram flour, sugar, ghee, cardamom.",
    image: "../assets/nine.png",
    gram: 100,
    featured: false,
    bestSelling: true,
  },
  {
    id: 13,
    name: "Mitho Mixed Sweets",
    price: "6",
    description:
      "Ingredients: Milk, milk Powder, Vegetable oil, Cream, dried nuts, shredded coconut, Self raising flour, Sugar, Cardamom.",
    image: "../assets/seven.png",
    gram: 100,
    featured: true,
    bestSelling: true,
  },
  {
    id: 14,
    name: "Mitho Mothichoor Laddu",
    price: "5.5",
    description:
      "Ingredients: Flour, Besan, cornflour, soda, sugar, Ghee, Edible food Colour.",
    image: "../assets/one.png",
    gram: 100,
    featured: true,
    bestSelling: true,
  },
  {
    id:15,
    name: "Mitho Peda",
    price: "6",
    description: "Ingredients: cashew nuts, sugar, cardamom, silver leaf .",
    image: "../assets/two.png",
    gram: 100,
    featured: true,
    bestSelling: true,
  },
  {
    id: 16,
    name: "Mitho Rasbari",
    price: "9",
    description: "Ingredients: Raw Cashew, Sugar, edible silver.",
    image: "../assets/eleven.png",
    gram: 100,
    featured: true,
    bestSelling: false,
  },
  {
    id: 17,
    name: "Mixed Laddu",
    price: "5.5",
    description: "Ingredients: Gram flour, sugar, ghee, cardamom.",
    image: "../assets/one.png",
    gram: 100,
    featured: false,
    bestSelling: true,
  },
  {
    id: 18,
    name: "Mixed Peda",
    price: "5",
    description:
      "Ingredients: Milk, milk Powder, Vegetable oil, Cream, dried nuts, shredded coconut, Self raising flour, Sugar, Cardamom.",
    image: "../assets/two.png",
    gram: 100,
    featured: true,
    bestSelling: true,
  },
  // {
  //   id: 19,
  //   name: "Nimki",
  //   price: "3.75",
  //   description:
  //     "Ingredients: Flour, Besan, cornflour, soda, sugar, Ghee, Edible food Colour.",
  //   image: two,
  //   gram: 100,
  //   featured: true,
  //   bestSelling: true,
  // },
  // {
  //   id: 20,
  //   name: "Selroti",
  //   price: "5.75",
  //   description: "Ingredients: cashew nuts, sugar, cardamom, silver leaf .",
  //   image: four,
  //   gram: 100,
  //   featured: true,
  //   bestSelling: true,
  // },
  
];

export default trending;
