# Generated by Django 4.2.23 on 2025-11-30 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0002_initial"),
        ("productapp", "0001_initial"),
        ("accountapp", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="blog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="blogapp.blogpost",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="productapp.product",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="merchantrating",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="merchantrating",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accountapp.merchant"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="action_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_content",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="actor_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actor_content",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "product")},
        ),
    ]
