# Generated by Django 4.2.23 on 2025-11-30 10:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("offer", "0001_initial"),
        ("productapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("quantity", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Delivery_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=150)),
                ("state", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=150)),
                ("street_address", models.CharField(max_length=150)),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+(?:[0-9]●?){6,14}[0-9]$",
                            )
                        ],
                    ),
                ),
                (
                    "delivery_option",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("order_id", models.PositiveIntegerField(default=12345)),
                ("coupon_used", models.BooleanField(default=False)),
                (
                    "coupon_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Ordered", "Ordered"),
                            ("Accepted", "Accepted"),
                            ("Being Delivered", "Being Delivered"),
                            ("Cancelled", "Cancelled"),
                            ("Received", "Received"),
                            ("Refund Requested", "Refund Requested"),
                            ("Refund Granted", "Refund Granted"),
                        ],
                        default="None",
                        max_length=150,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("ordered", models.BooleanField(default=False)),
                ("delivered_date", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "billing_adderess",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_address",
                        to="checkoutapp.delivery_detail",
                    ),
                ),
                ("cart", models.ManyToManyField(to="checkoutapp.cart")),
                (
                    "delivery_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="checkoutapp.delivery_detail",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Offer applied at the time of purchase",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="offer.buzzoffer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Ordered", "Ordered"),
                            ("Accepted", "Accepted"),
                            ("Being Delivered", "Being Delivered"),
                            ("Cancelled", "Cancelled"),
                            ("Received", "Received"),
                            ("Refund Requested", "Refund Requested"),
                            ("Refund Granted", "Refund Granted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "proof_image",
                    models.ImageField(blank=True, null=True, upload_to="order_proofs/"),
                ),
                (
                    "proof_document",
                    models.FileField(blank=True, null=True, upload_to="order_docs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="checkoutapp.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Disabled", "Disabled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("product_name", models.CharField(max_length=250)),
                ("product_id", models.CharField(max_length=250)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sub_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_image", models.TextField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Ordered", "Ordered"),
                            ("Accepted", "Accepted"),
                            ("Being Delivered", "Being Delivered"),
                            ("Cancelled", "Cancelled"),
                            ("Received", "Received"),
                            ("Refund Requested", "Refund Requested"),
                            ("Refund Granted", "Refund Granted"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "giftcard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="offer.giftcard",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productapp.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_order",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.ManyToManyField(to="checkoutapp.orderitem"),
        ),
    ]
