# Generated by Django 4.2.23 on 2025-11-30 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSuspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateTimeField(auto_now_add=True)),
                ("to_date", models.DateTimeField()),
                ("reason", models.CharField(max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=uuid.UUID("ec0bf2c9-8322-4045-b918-1770e8e764c1"),
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspended_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeactivateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateTimeField(auto_now_add=True)),
                ("to_date", models.DateTimeField(blank=True, null=True)),
                ("reactivate_date", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deactivate History",
                "verbose_name_plural": "Deactivate Histories",
                "ordering": ("-from_date",),
            },
        ),
    ]
