"""
Django settings for cagtubuzz project.




Generated by 'django-admin startproject' using Django 3.2.12.




For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/




For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from email.policy import default
from pathlib import Path
from firebase_admin import initialize_app, credentials
import os
from decouple import config
import uuid
import stripe


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-y_mntl@isu+9-$tnkryo!!b!8)o%d-4)_)4n)nmvd)4&+j+gv7",
)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)
use_s3 = config("USE_S3", default=False, cast=bool)

if use_s3:
    ALLOWED_HOSTS = [
        "api.mithosweets.com",
        "https://api.mithosweets.com",
        "localhost",
        "127.0.0.1",
        "192.168.0.192",
        "192.168.0.184",
        "rddmbhr4-8000.inc1.devtunnels.ms",
    ]

else:
    ALLOWED_HOSTS = ["*"]


CSRF_TRUSTED_ORIGINS = [
    "http://0.0.0.0:8005",
    "http://192.168.0.189:8005",
    "http://localhost:8005",
    "http://127.0.0.1:8005",
    "https://api.mithosweets.com",
    "https://l7141dfh-3001.inc1.devtunnels.ms",
]
# USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# Security settings for production


SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True


if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# For modern browsers
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"


AUTH_USER_MODEL = "accountapp.User"
SOCIAL_AUTH_USER_MODEL = "accountapp.User"

# AUTH_USER_MODEL = ''
# Application definition


INSTALLED_APPS = [
    "django_crontab",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "debug_toolbar",
    # auth & social auth
    "rest_framework.authtoken",
    # 'rest_framework_swagger',
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "dj_rest_auth",
    "allauth",
    "allauth.account",
    "dj_rest_auth.registration",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "django_filters",
    "storages",
    # cleanup
    "django_cleanup.apps.CleanupConfig",
    # social_auth needed
    "social_django",
    "ckeditor",
    "ckeditor_uploader",
    # buzz apps
    "apps.core",
    "apps.accountapp",
    "apps.customersupportapp",
    "apps.productapp",
    "apps.checkoutapp",
    "apps.paymentapp",
    "apps.dashboardapp",
    "apps.offer",
    "apps.locales",
    "apps.security",
    "apps.master",
    "apps.activity",
    "apps.history",
    # for handling notifications
    "apps.notifications",
    "fcm_django",
    # for social_auth custom app
    "apps.errlogs",
    "apps.social_app",
    "apps.blogapp",
    "apps.analyticsapp",
    "apps.vendor",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #'allauth.account.middleware.AccountMiddleware',
]


ROOT_URLCONF = "cagtubuzz.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "cagtubuzz.wsgi.application"


DB_ENGINE = config("DB_ENGINE", default="django.db.backends.postgresql")


if use_s3:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": (
                BASE_DIR / "db.sqlite3"
                if DB_ENGINE == "django.db.backends.sqlite3"
                else config("DB_NAME", default="buzz")
            ),
            "USER": config("DB_USER", default="postgres"),
            "PASSWORD": config("DB_PASSWORD", default="dbms@123"),
            "HOST": config("DB_HOST", default="localhost"),
            "PORT": config("DB_PORT", cast=int, default=5432),
            'OPTIONS': {
                'options': '-c client_encoding=UTF8',
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": (
                BASE_DIR / "db.sqlite3"
                if DB_ENGINE == "django.db.backends.sqlite3"
                else config("DB_NAME", default="buzz")
            ),
            "USER": config("DB_USER", default="postgres"),
            "PASSWORD": config("DB_PASSWORD", default="dbms@123"),
            "HOST": config("DB_HOST", default="localhost"),
            "PORT": config("DB_PORT", cast=int, default=5432),
            'OPTIONS': {
                'options': '-c client_encoding=UTF8',
            },
        }
    }
# dbms@123
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/


LANGUAGE_CODE = "en-us"


TIME_ZONE = "Asia/Kathmandu"


USE_I18N = True


USE_L10N = True


USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ===========================[ rest framework settings ]==========================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "apps.core.pagination.CustomPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}
# ===========================[ Google Oauth settings ]==========================

GOOGLE_RECAPTCHA_SECRET_KEY = "6Le_4sQeAAAAACWf3sEf3qHlxGybukPfcvCH7-N_"


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config(
    "SOCIAL_AUTH_GOOGLE_CLIENT_KEY",
    default="486423748906-4c99rt3gnim1ihn85pgj5r1t9obnqn92.apps.googleusercontent.com",
)

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config(
    "SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET", default="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"
)

SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = [
    ("name", "name"),
    ("email", "email"),
    ("picture", "picture"),
    ("link", "profile_url"),
]
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ["email", "profile"]

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "social_core.backends.google.GoogleOAuth2",
    "allauth.account.auth_backends.AuthenticationBackend",  # allauth
)

ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_SIGNUP_URL = None
SITE_ID = 1


SOCIALACCOUNT_ADAPTER = "apps.social_app.adapters.CustomSocialAccountAdapter"

ACCOUNT_INACTIVE_REDIRECT_URL = "/api/v1/social_app/account_inactive/"

# JWT

from datetime import timedelta

REST_USE_JWT = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=config("ACCESS_TOKEN_LIFETIME_MINUTES", default=555555, cast=int)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        minutes=config("REFRESH_TOKEN_LIFETIME_MINUTES", default=555555, cast=int)
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}


# swagger security settings
# SWAGGER_SETTINGS = {
#     'SECURITY_DEFINITIONS': {
#         'Basic': {
#             'type': 'basic'
#         },
#         'Bearer': {
#             'type': 'apiKey',
#             'name': 'Authorization',
#             'in': 'header'
#         }
#     }
# }
SPECTACULAR_SETTINGS = {
    "TITLE": "Buzz API",
    "DESCRIPTION": "Keep on Buzzing!",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # side car settings
    "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    "COMPONENT_SPLIT_REQUEST": True,
    "CAMELIZE_NAMES": True,
    "SCHEMA_PATH_PREFIX": r"/api/{version}/",
    # OTHER SETTINGS
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        "displayRequestDuration": True,
        "filter": True,
        "tryItOutEnabled": True,
    },
}


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOWED_ORIGINS = [
    "https://l7141dfh-3001.inc1.devtunnels.ms",
]


if use_s3:
    # Amazon SES
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = config("EMAIL_HOST", default="email-smtp.ap-southeast-2.amazonaws.com")
    EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = config("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
else:
    # Gmail for local/dev
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="your_gmail@gmail.com")
    EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Twilio OTP Settings
TWILIO_ACCOUNT_SID = "AC843fdc0fc3b7313aa2b1b5a2d0655035"
TWILIO_AUTH_TOKEN = "334fd7a8e46a01a914516095525eff73"
TWILIO_DEFAULT_CALLERID = "+12172926441"


# Recaptcha secret key


# EMAIL_HOST = 'smtp.mailtrap.io'
# EMAIL_HOST_USER = '83030585db2d3a'
# EMAIL_HOST_PASSWORD = '79acf37b5232ff'
# EMAIL_PORT = '2525'


CRONJOBS = [("*/1 * * * *", "apps.productapp.cron.my_cron_job", ">> /file.log")]


STRIPE_SECRET_KEY = "sk_test_51L7teSGYAAahex2y8DHDdXLb3QH5oo6iAlInwSNu7Su2BDMMCecaLXnRcYM833ohEnKOAYoxhv2tWA8BWt5pCGUO00w2FFFanq"


SITE_URL = "http://localhost:3000"


# Webhook event settings
HOOK_EVENTS = {
    "notification.added": "notifications.Notification.created",
}


# firebase credentials and intialization of app
# GOOGLE_APPLICATION_CREDENTIALS = os.path.join(BASE_DIR, "credentials.json")


# cred = credentials.Certificate(os.path.join(PROJECT_APP, '../credentials.json'))
# firebase_admin.initialize_app(cred)
cred = credentials.Certificate(os.path.join(BASE_DIR, "credentials.json"))
FIREBASE_APP = initialize_app(cred)


FCM_DJANGO_SETTINGS = {
    # "FCM_SERVER_KEY": "AAAAXPrHJh4:APA91bH6h83gceYeuzQZjaZMx6z5NMYDJwNkWGVv6A4HZAZC-S-KiaWI6z6JaVy7O6DAidWxKAtRb1sJ66lJkhPGQVL2ekzaHyzHJ4aWxkYJv4-BDQxssuO9INW85PhdGVPU10v40C_C",
    # default: _('FCM Django')
    "APP_VERBOSE_NAME": "web-buzz-nofify",
    # true if you want to have only one active device per registered user at a time
    # default: False
    "ONE_DEVICE_PER_USER": False,
    # devices to which notifications cannot be sent,
    # are deleted upon receiving error response from FCM
    # default: False
    "DELETE_INACTIVE_DEVICES": True,
}

TESTPASSWORD = config("TESTPASSWORD", default="testpassword")


# frontend and backend app domains
APP_DOMAIN = config("APP_DOMAIN", default="https://sandbox.buzz.api.cagtu.io")
WEB_UI_URL = config("WEB_UI_URL", default="http://192.168.0.182:3000")


DEFAULT_UUID = config("DEFAULT_UUID", default="c5b2d6f2-6121-4875-a353-b960b952e5d4")
DEFAULT_UUID = uuid.UUID(DEFAULT_UUID)


DEFAULT_FK = 1


PAYMENT_GATEWAY = {
    "paypal": {
        "username": config(
            "PAYPAL_USERNAME", default="FLAVORsb-sb-0ymf220579022@business.example.com"
        ),
        "client_id": config(
            "PAYPAL_CLIENT_ID",
            default="AYr4y0qTe8T8uhVHypMAie3C9luI1joPojdMoeFo7P0ZYY52fpPiCh0AMdzYKHC6gl3z0GjF5zEHgA13",
        ),
        "secret_key": config(
            "PAYPAL_CLIENT_SECRET",
            default="EGaVwoUQa7TFJS__6xp7Ga2GV4etavi4tbvPy8khtf3YVCjE8T7mVNSC_az9vJV4RkdbywEwrryMPu21",
        ),
        "sandbox": config("PAYPAL_SANDBOX", default=True, cast=bool),
    },
    "khalti": {
        "public_key": config(
            "KHALTI_PUBLIC_KEY", default="6540c9d7c4664ed7a3d1eb3840dddd2d"
        ),
        "secret_key": config(
            "KHALTI_SECRET_KEY", default="b15a076f8d3d49a5aeb7782a5bfe28e9"
        ),
        "sandbox": config("KHALTI_SANDBOX", default=True, cast=bool),
    },
}

KHALTI_PUBLIC_KEY = PAYMENT_GATEWAY["khalti"]["public_key"]
KHALTI_SECRET_KEY = PAYMENT_GATEWAY["khalti"]["secret_key"]
KHALTI_SANDBOX = PAYMENT_GATEWAY["khalti"]["sandbox"]


# REDIS_SERVER = config("REDIS_SERVER", default="cache-server:6380")
REDIS_SERVER = config("127.0.0.1:6379", default="127.0.0.1:6379")


STRIPE_API_KEY = config(
    "STRIPE_API_KEY",
    default="pk_test_51LZ7lvHoTWj1Tzy1ECtPmuG9LXziKXoDjNlxJaAEynTbTqTVVaL01fTVrPOg3zRR8S3Dn1L1H6etpmjKQJmcehw400tufj9t2R",
)
STRIPE_API_SECRET = config(
    "STRIPE_API_SECRET",
    default="sk_test_51LZ7lvHoTWj1Tzy1unF0rBkhsx77B2odabtan1QY71c9GZbvvY6Yv2xQp5YEDz4t8JesgBguPuHaPMCAG0iUjHMb00R7IEo12O",
)
stripe.api_key = STRIPE_API_SECRET


# redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_SERVER}/",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,
                "retry_on_timeout": True,
            },
        },
    }
}


CELERY_BROKER_URL = f"redis://{REDIS_SERVER}/"
CELERY_RESULT_BACKEND = f"redis://{REDIS_SERVER}/"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"


MAIL_MAX_RETRIES = 3
MAIL_RETRY_DELAY = 200


import base64
import os


# generate a random key once
FIELD_ENCRYPTION_KEY = base64.urlsafe_b64encode(os.urandom(32))


"""AWS media files section"""


if use_s3:
    # aws settings
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default="AKIAQWSU6XM3DLRBDV4I")
    AWS_SECRET_ACCESS_KEY = config(
        "AWS_SECRET_ACCESS_KEY", default="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"
    )
    AWS_STORAGE_BUCKET_NAME = config(
        "AWS_STORAGE_BUCKET_NAME", default="buzz-media-files"
    )
    # AWS_DEFAULT_ACL = 'public-read'
    AWS_DEFAULT_ACL = None  # very important
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    AWS_S3_SIGNATURE_NAME = "s3v4"
    AWS_S3_REGION_NAME = "ap-south-1"
    AWS_S3_VERIFY = True
    # s3 static settings
    AWS_LOCATION = "static"
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
    STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    # s3 public media settings
    PUBLIC_MEDIA_LOCATION = "media_files"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/"
    DEFAULT_FILE_STORAGE = "utils.storage_backends.PublicMediaStorage"

    # s3 private media settings
    PRIVATE_MEDIA_LOCATION = "private_media_files"
    PRIVATE_FILE_STORAGE = "utils.storage_backends.PrivateMediaStorage"
else:
    STATIC_URL = "/static/"
    # Default primary key field type
    # https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

    if DEBUG:
        STATICFILES_DIRS = [BASE_DIR / "static"]
        MEDIA_URL = "/media/"
        MEDIA_ROOT = BASE_DIR / "media"

    else:
        STATIC_ROOT = BASE_DIR / "static"
        MEDIA_URL = "/media/"
        MEDIA_ROOT = BASE_DIR / "media"


CKEDITOR_UPLOAD_PATH = "uploads/"
